name: Generate mods list markdown

on:
  push:
    branches:
      - master

jobs:
  Generate-Markdown:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          path: master

      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          repository: neos-modding-group/neos-modding-group.github.io
          path: gh-pages
    
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3"

      - name: generate readme
        run: ./master/gen_readme.py

      - name: commit
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add --force mods.md
          git commit -m "Update mod list"
          git push origin gh-pages
